name: dotnet-core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore csharp
    - name: Build
      run: dotnet build csharp/Main.sln -c Release --no-restore
    - name: Test
      run: dotnet test csharp/Main.sln --no-restore --verbosity normal
